config/routes.rb
Rails.application.routes.draw do
 resources :sandwiches, only: [:index, :show], controller: "sandwich_views"
 scope "/api" do
    resources :sandwiches
    resources :ingredients
    post "/sandwiches/:id/ingredients/add" => "sandwiches#add_ingredient"
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
	has_many :sandwich_ingredients
	has_many :sandwiches, through: "sandwich_ingredients"
end

app/models/sandwich.rb
class Sandwich < ApplicationRecord
	has_many :sandwich_ingredients
	has_many :ingredients, through: "sandwich_ingredients"
end

app/models/sandwich_ingredient.rb
class SandwichIngredient < ApplicationRecord
	belongs_to :sandwich
	belongs_to :ingredient
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
	protect_from_forgery with: :null_session
	def index
		ingredients = Ingredient.all
		render json: ingredients
	end

	def create
		ingredient = Ingredient.create(ingredient_params)
		render json: ingredient
	end
	def show
		ingredient = Ingredient.find(params[:id])
		render json: ingredient
	end

	def update
		ingredient = Ingredient.find(params[:id])
		ingredient.update(ingredient_params)
		render json: ingredient
	end

	def destroy
		ingredient = Ingredient.find(params[:id])
		ingredient.destroy
		render json: ingredient
	end

	private
	
	def ingredient_params
		params.require(:ingredient)
		.permit(:name, :bread_type)
	end

end

app/controllers/sandwich_views_controller.rb
class SandwichViewsController < ApplicationController
	
	def index
		@sandwichesa = Sandwich.all
		render "index"
	end

	def show
		@thesandwich = Sandwich.find(params[:id])
		@theIngredients = Ingredient.all
		render "show"
	end

end

app/controllers/sandwiches_controller.rb
class SandwichesController < ApplicationController
	protect_from_forgery with: :null_session
	def index
		sandwiches = Sandwich.all
		render json: sandwiches
	end

	def create
		sandwich = Sandwich.create(sandwich_params)
		render json: sandwich
	end
	def show
		sandwich = Sandwich.find(params[:id])
		sandwichid = sandwich.id
		# @sandwichIngredients= sandwich.ingredients
		ingredients = SandwichIngredient.where(sandwich_id: sandwichid)
		# sandwichIngredients each do |item|
		# 	sandwich.total_calories += item.calories
		# end
		render json: sandwich.to_json(include: :ingredients)
	end

	def update
		sandwich = Sandwich.find(params[:id])
		sandwich.update(sandwich_params)
		render json: sandwich
	end

	def destroy
		sandwich = Sandwich.find(params[:id])
		sandwich.destroy
		render json: sandwich
	end

	def add_ingredient
		sandwich = Sandwich.find(params[:id])
		ingredient = Ingredient.find(params[:ingredient_id])
		sandwich.ingredients.push(ingredient)
		sandwich.total_calories += ingredient.calories
		sandwich.save
		render json: sandwich.to_json(include: :ingredients)
	end

	private

	def sandwich_params
		params.require(:sandwich)
		.permit(:name, :bread_type, :total_calories)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/sandwich_views_helper.rb
module SandwichViewsHelper
end

app/helpers/sandwiches_helper.rb
module SandwichesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sandwichr</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sandwich_views/index.html.erb
<h2>List of Sandwiches</h2>

<ul>
<%	 @sandwichesa.each do |x| %>
<li><%= link_to "#{x.name}", sandwich_path(x) %></li>
<% end %>
</ul>

app/views/sandwich_views/show.html.erb
<div data-sandwich-id="<%= @thesandwich.id %>"><%= @thesandwich.name %></div>

<ul>
<li>Bread: <%= @thesandwich.bread_type %></li>
<li>Total Calories: <%= @thesandwich.total_calories %></li>
<li>Ingredients: 
		<ul class='js-ingredient-list'>
			<% @thesandwich.ingredients.each do |an_ingredient| %>
			<li><%= an_ingredient.name %></li>
			<% end %>
			</ul>
			</li>

</ul>

<h4>Add Ingredients </h4>
<ul>
<% @theIngredients.each do |an_ingredient| %>
<li><button class="js-ingredient" data-sandwich-id="<%= @thesandwich.id %>" data-ingredient-id="<%= an_ingredient.id %>">
	<%= an_ingredient.name %></button></li>
	<% end %>
</ul>	

app/views/sandwiches/home.html.erb
<h1>home</h1>